### ISSUE TITLE
Tareas

### ISSUE THREAD

**Issue by Oswaldofm17** [UG-Mobile2016/Tareas#2]
Recordar agregar tareas de investigación de Patrones de Diseño.

**Comment by Oswaldofm17** [comment]
Patrón singleton, factory metod, patrón builder...

**Comment by Oswaldofm17** [comment]
Investigar que es ADB en android

**Comment by Oswaldofm17** [comment]
Operador final en java

**Comment by Oswaldofm17** [comment]
Que lenguajes soporta sobrecarga de operadores

**Comment by Oswaldofm17** [comment]
Como funciona Gradle

**Comment by Oswaldofm17** [comment]
Inyección de dependencias en desarrollo de software

**Comment by tzohpilotl** [comment]
¿Cual es la tarea en sí? ¿Para cuándo es?

**Comment by caralasa136** [comment]
Investigar todas esas definiciones y subirlas a repos, si no me equivoco es para el jueves de la semana entrante 👍

**Comment by JuanCrg90** [comment]
En rato actualizo el archivo de tareas, será una sola investigación para que no hagan tanto repositorio.

**Comment by JuanCrg90** [comment]
Tarea actualizada gracias por la nota @Oswaldofm17
